version: "3.7"
services: 
  app:
    build:
      context: .
      # dockerfile: ./Dockerfile
    image: sappachok/docker-laravel-oci8
    container_name: 'laravelapp'
    tty: true
    command:  php artisan serve --host=0.0.0.0 --port=9000
    ports:
      - 8080:80
      - 9000:9000
    volumes:
      - c://xampp3//htdocs//laravel//laravel-ora:/var/www/html
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ngx
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

#Docker Networks
networks:
  app-network:
    driver: bridge