version: "3.7"
services: 
  app:
    image: sappachok/docker-laravel-oci8
    container_name: 'laravelapp'
    tty: true
    #command:  php artisan serve --host=0.0.0.0 --port=9000
    #ports:
    #  - 8080:80
    #  - 9000:9000
    working_dir: /var/www/
    volumes:
      - d://repo//laravelapp:/var/www
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: ngx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

#Docker Networks
networks:
  app-network:
    driver: bridge